USE `canban`;

CREATE TABLE IF NOT EXISTS `BOARDS` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(45) NOT NULL,
	`PARENT` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `fk_boards_parent` (`PARENT`),
	CONSTRAINT `fk_parent` FOREIGN KEY (`PARENT`) REFERENCES `BOARDS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `BOARDHASTICKET` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ID_BOARD` int(11) NOT NULL,
	`ID_TICKET` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_boardhasticket_board` FOREIGN KEY (`ID_BOARD`) REFERENCES `BOARDS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT `fk_boardhasticket_ticket` FOREIGN KEY (`ID_TICKET`) REFERENCES `TICKETS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `USERHASBOARD` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ID_USER` int(11) NOT NULL,
	`ID_BOARD` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_userhasboard_user` FOREIGN KEY (`ID_USER`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT `fk_userhasboard_board` FOREIGN KEY (`ID_BOARD`) REFERENCES `BOARDS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GROUPHASBOARD` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`ID_GROUP` int(11) NOT NULL,
	`ID_BOARD` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_grouphasboard_group` FOREIGN KEY (`ID_GROUP`) REFERENCES `GROUPS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT `fk_grouphasboard_board` FOREIGN KEY (`ID_BOARD`) REFERENCES `BOARDS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;